# Generated by Django 3.2.5 on 2021-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
