# Generated by Django 3.2.5 on 2021-08-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0009_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shopitapp.ram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shopitapp.storage'),
            preserve_default=False,
        ),
    ]
