# Generated by Django 3.2.5 on 2021-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0014_product_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
