# Generated by Django 3.2.5 on 2021-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0021_product_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_advert', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
