# Generated by Django 3.2.5 on 2021-09-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0022_auto_20210910_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardadvert',
            name='leaderboard_advert',
        ),
        migrations.AddField(
            model_name='leaderboardadvert',
            name='leaderboard_banner1',
            field=models.ImageField(blank=True, default='banner_default.jpg', null=True, upload_to='images/leaderbanners'),
        ),
        migrations.AddField(
            model_name='leaderboardadvert',
            name='leaderboard_banner2',
            field=models.ImageField(blank=True, default='banner_default.jpg', null=True, upload_to='images/leaderbanners'),
        ),
        migrations.AddField(
            model_name='leaderboardadvert',
            name='leaderboard_banner3',
            field=models.ImageField(blank=True, default='banner_default.jpg', null=True, upload_to='images/leaderbanners'),
        ),
    ]
