# Generated by Django 3.2.5 on 2021-09-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0023_auto_20210910_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaderboardAdvert',
            new_name='Leaderboard',
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='leaderboard_banner1',
            new_name='leaderbanner1',
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='leaderboard_banner2',
            new_name='leaderbanner2',
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='leaderboard_banner3',
            new_name='leaderbanner3',
        ),
    ]
