# Generated by Django 3.2.8 on 2021-10-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0026_auto_20211012_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backcamera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FrontCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontcamera', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='backcamera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopitapp.backcamera'),
        ),
        migrations.AddField(
            model_name='product',
            name='frontcamera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopitapp.frontcamera'),
        ),
    ]
