# Generated by Django 3.2.8 on 2021-10-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0029_product_newginindex'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='NewGinIndex',
        ),
    ]
